config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (handler404, handler500)

handler404 = 'common.views.page_not_found'
handler500 = 'common.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('group/', include('group.urls')),
    path('', include('user.urls')),
    path('qna/', include('qna.urls')),
    # path('account/', include('allauth.urls')), #account.urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path
from . import views
from .views import FileDownloadView

app_name = 'qna'

urlpatterns = [
    #path('',views.QuestionView.as_view(), name='question_list'),
    path('',views.question_list, name='question_list'),
    path('search_result/', views.search_result, name='search_result'),
    path('question_create/', views.question_create, name='question_create'),
    #path('question_create/', views.FileFieldFormView.as_view(), name='question_create'),
    #path('<int:pk>/', views.question_detail, name='question_detail'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('<int:pk>/update', views.question_update, name='question_update'),
    path('<int:pk>/delete', views.question_delete, name='question_delete'),
    path('answer_ajax/', views.answer_ajax, name='answer_ajax'),
    path('reply_ajax/', views.reply_ajax, name='reply_ajax'),
    path('question_like_ajax/', views.question_like_ajax, name='question_like_ajax'),
    path('answer_like_ajax/', views.answer_like_ajax, name='answer_like_ajax'),
    path('answer_delete_ajax/', views.answer_delete_ajax, name='answer_delete_ajax'),
    path('answer_edit_ajax/', views.answer_edit_ajax, name='answer_edit_ajax'),
    path('answer_edit_submit_ajax/', views.answer_edit_submit_ajax, name='answer_edit_submit_ajax'),
    path('<int:pk>/download/', FileDownloadView.as_view(), name="download"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.main, name="main"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.log_out, name="logout"),
    path('signup/', views.sign_up, name="signup"),
    path('activate/<uid64>/<token>/', views.activate, name="activate"),
    path('mypage/', views.my_page, name="mypage"),
    path('mypage/revise/', views.my_page_revise, name="mypage_revise"),
    path('mypage/question/',
         views.QuestionView.as_view(), name="mypage_question"),
    path('mypage/answer/', views.AnswerView.as_view(), name="mypage_answer"),
    path('mypage/reward/<int:pk>/', views.my_page_reward, name="mypage_reward"),
    path('mypage/reward/representative_ajax/',
         views.representative_reward_ajax, name="representative_reward_ajax"),
    path('mypage/reward/date_ajax/',
         views.date_reward_ajax, name="date_reward_ajax"),
    path('mypage/point/', views.PointView.as_view(), name="mypage_point"),
    path('mypage/alert/', views.AlertView.as_view(), name="mypage_alert"),
    path('mypage/alert/check_ajax/',
         views.check_alert_ajax, name="check_alert_ajax"),
    path('mypage/alert/check_all_ajax/',
         views.check_all_alert_ajax, name="check_all_alert_ajax"),
    path('mypage/alert/load_new_ajax/',
         views.load_new_alert_ajax, name="load_new_alert_ajax"),
    path('<int:pk>/public_userpage/',
         views.public_userpage, name='public_userpage'),
    path('<int:pk>/public_userpage/question/',
         views.QuestionView.as_view(), name="public_userpage_question"),
    path('<int:pk>/public_userpage/answer/',
         views.AnswerView.as_view(), name="public_userpage_answer"),
    path('<int:pk>/public_userpage/reward/',
         views.my_page_reward, name="public_userpage_reward"),
    path('group_wait_profile/', view=views.group_wait_profile,
         name='group_wait_profile'),
    path('drop/', views.drop, name="drop"),
    path('drop_success/', views.drop_success, name="drop_success"),
    path('periodic_tasks/', views.periodic_tasks, name="periodic_tasks"),
    path('periodic_tasks_immediate/', views.periodic_tasks_immediate,
         name="periodic_tasks_immediate"),
    path('initialize_rewards/', views.initialize_rewards,
         name="initialize_rewards"),
    path('password_change/search/',
         views.password_change_search, name="password_change_search"),
    path('password_change/<uid64>/<token>/',
         views.password_change, name="password_change"),
]

qna/forms.py
from django import forms
from .models import *

class QuestionForm(forms.ModelForm):
    img_recent = forms.CharField(required=False)
    file_recent = forms.CharField(required=False)
    class Meta:
        model = Question
        exclude = ('hit', 'like_user', 'user')

qna/views.py
#-*-coding:utf-8-*-
from datetime import date
from wsgiref.simple_server import sys_version
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from django.db.models import Q
import json
import shutil, os
from django.http import JsonResponse, FileResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator 
from django.db.models import Count
from django.contrib import messages
from django.views.generic import ListView, View
from hitcount.views import HitCountDetailView
from django.views.generic.detail import SingleObjectMixin
from django.core.files.storage import FileSystemStorage
import mimetypes
from user.update import *
from django.contrib.auth.models import AnonymousUser

basic_tags = ['동작', '형태', '소리', '이벤트', '제어',' 감지', '연산', '변수', '내 블록', '기타']

def question_tag_filter(questions, tag_filter_by_list):
    num = len(tag_filter_by_list)
    if num == 1:
        questions= questions.filter(s_or_e_tag=tag_filter_by_list[0]) 
    elif num == 2:
        questions= questions.filter(Q(s_or_e_tag=tag_filter_by_list[0]) | Q(s_or_e_tag=tag_filter_by_list[1]))
    elif num==3:
        pass
    return questions

def question_answer_filter(questions, answer_filter_by):
    if answer_filter_by == 'NOT_ANSWERED':
        questions_list = [question.id for question in questions if not question.answer_set.filter(is_deleted = False, answer_depth = 0).exists()]
        questions = Question.objects.filter(id__in = questions_list)
    else:
        # TODO 
        # 답변 여부 필터 할 때 진짜 답변만 고려할 수 있도록 필터 
        questions_list = [question.id for question in questions if question.answer_set.filter(is_deleted = False, answer_depth = 0).exists()]
        questions = Question.objects.filter(id__in = questions_list)
    return questions

### Error messages
# 이름이 user.view에 있는 것과 겹쳐서, 헷갈릴 여지가 있을 것 같습니다.
# QnaErrorMessages가 좋을 것 같습니다.
# TODO : validation 체크할 때 request 객체와 form을 넘겨주는 건 어떨까요?
# TODO : 넘겨주는 인자가 너무 많고, 순서 헷갈릴 여지도 있어보입니다.
class QnaErrorMessages():
    title, content, image, attached_file, s_or_e_tag, tags = '', '', '', '', '', ''

    def validation_check(self, request, command):
        if 'create' in command or 'update' in command:
            if not request.POST.get('title'):
                self.title = '제목을 입력해주세요'
            elif len(request.POST.get('title'))>50:
                self.title = '제목은 50자 이내로 입력해주세요'
            if not request.POST.get('content'):
                self.content = '내용을 입력해주세요'
            if not request.POST.get('s_or_e_tag'):
                self.s_or_e_tag = '카테고리를 선택해주세요'

    def has_error(self):
        return self.title or self.content or self.image or self.attached_file or self.s_or_e_tag or self.tags

class OriginalInformation():
    def remember(self, request, command):
        self.title = request.POST.get('title')
        self.content = request.POST.get('content')
        self.image = request.FILES.get('image')
        self.attached_file = request.FILES.get('attached_file')
        self.s_or_e_tag = request.POST.get('s_or_e_tag')
        self.tags = request.POST.getlist('detail_tag')
        self.command = command

##### view 시작

def question_list(request):
    questions = Question.objects.all().order_by('-created_at')
    page = request.GET.get('page', '1')    # 페이지
    #questions = Question.objects.order_by('-created_at')   # [기본 정렬] 최신순으로 정렬

    # 게시글 필터
    tag_filter_by = request.GET.getlist('tag_filter_by')
    if tag_filter_by:
        questions = question_tag_filter(questions, tag_filter_by)
    answer_filter_by = request.GET.get('answer_filter_by')
    if answer_filter_by:
        questions = question_answer_filter(questions, answer_filter_by)

    # 게시물 정렬
    sort_by = request.GET.get('sort', 'recent')
    if sort_by == 'recent':    # 최신순
        questions = questions.order_by('-created_at')
    elif sort_by == 'liked':   # 좋아요순
        questions = questions.annotate(total_likes=Count('like_user')).order_by('-total_likes')
    elif sort_by == 'view':    # 조회수순
        questions = questions.order_by('-hit_count_generic__hits')
    # 페이징 처리
    paginator = Paginator(questions, 10)    # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    
    dict ={}
    for page in page_obj:
        answers_count = Answer.objects.filter(question_id =page, answer_depth=0, is_deleted = False).count()
        dict[page] = answers_count
    ctx = {
        'questions': page_obj,
        'sort_by':sort_by,
        'filter_by':tag_filter_by+[answer_filter_by],
        'question_answer_count':dict,
    }

    return render(request, 'qna/question_list.html', context=ctx)

def search_result(request):
    if not request.GET.get('search') or request.GET.get('search').isspace():
        return redirect('qna:question_list')
    if 'search' in request.GET:
        query = request.GET.get('search')
        questions = Question.objects.all().filter(
            Q(title__icontains=query) | # 제목으로 검색
            Q(content__icontains=query)| # 내용으로 검색
            Q(tags__tag_name__icontains=query) # 태그로 검색
        )

    # 게시물 정렬
    sort_by = request.GET.get('sort', 'recent')
    if sort_by == 'recent':    # 최신순
        questions = questions.order_by('-created_at')
    elif sort_by == 'liked':   # 좋아요순
        questions = questions.annotate(total_likes=Count('like_user')).order_by('-total_likes')
    elif sort_by == 'view':    # 조회수순
        questions = questions.order_by('-hit_count_generic__hits')

    page = request.GET.get('page', '1')    # 페이지
    paginator = Paginator(questions, 10)    # 페이지당 5개씩 보여주기
    page_obj = paginator.get_page(page)
    
    dict ={}
    for page in page_obj:
        answers_count = Answer.objects.filter(question_id =page, answer_depth=0, is_deleted = False).count()
        dict[page] = answers_count

    ctx = {
        'query': query, 
        'questions': page_obj, 
        'question_answer_count':dict,
        'sort_by':sort_by,
    }
    return render(request, 'qna/search_result.html', context=ctx)



def question_create(request):
    user = request.user
    if user == AnonymousUser():
        return redirect('user:main')

    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        
        error_messages = QnaErrorMessages()

        error_messages.validation_check(request, ['create'])
        if not error_messages.has_error():
            question = Question.objects.create(
                title=request.POST.get('title'),
                content=request.POST.get('content'),
                # image=request.FILES.get('image'),
                # #attached_file=form.data['attached_file'],
                # attached_file=request.FILES.get('attached_file'),
                s_or_e_tag=request.POST.get('s_or_e_tag'),
                user=request.user
            )
            
            tags = request.POST.getlist('detail_tag')
            for tag in tags:
                if len(QnaTag.objects.filter(tag_name=tag)) == 0:
                    QnaTag.objects.create(
                        tag_name = tag,
                    )

                # QnaTag db에 없으면 오류 발생
                newtag = get_object_or_404(QnaTag, tag_name=tag)
                question.tags.add(newtag)

            # image, file 부분
            date_dir = datetime.today().strftime('/%Y/%m/%d/')
            os.makedirs('./media/qna/uploads' + date_dir, exist_ok=True)

            if request.FILES.get('image'):
                question.image = request.FILES.get('image')
            elif request.POST['img_recent']:
                os.makedirs('./media/temp/', exist_ok=True)
                shutil.copyfile('./media/temp/{}'.format(request.POST['img_recent']),
                                './media/qna/uploads'+ date_dir +'{}'.format(request.POST['img_recent'])) ###
                question.image =  './qna/uploads'+ date_dir + '{}'.format(request.POST['img_recent']) ###

                ## temp 파일 삭제
                if os.path.isfile('./media/temp/{}'.format(request.POST['img_recent'])):
                    os.remove('./media/temp/{}'.format(request.POST['img_recent']))
        
            if request.FILES.get('attached_file'):
                question.attached_file = request.FILES.get('attached_file')
            elif request.POST['file_recent']:
                os.makedirs('./media/temp/', exist_ok=True)
                shutil.copyfile('./media/temp/{}'.format(request.POST['file_recent']),
                                './media/qna/uploads'+ date_dir +'{}'.format(request.POST['file_recent'])) ###
                question.attached_file = './qna/uploads'+ date_dir +'{}'.format( request.POST['file_recent']) ###

                ## temp 파일 삭제
                if os.path.isfile('./media/temp/{}'.format(request.POST['file_recent'])):
                    os.remove('./media/temp/{}'.format(request.POST['file_recent']))

            question.save()
            update_question(question, request.user)

            

            return redirect('qna:question_detail', question.pk)

        else:
            global basic_tags
            tags = request.POST.getlist('detail_tag')

            basic_tag_names = []
            extra_tag_names = []
            for tag in tags:
                if tag in basic_tags:
                    basic_tag_names.append(tag)
                else:
                    extra_tag_names.append(tag)

            original_information = OriginalInformation()
            original_information.remember(request, ['create'])

            if request.FILES.get('image'):
                os.makedirs('./media/temp/', exist_ok=True)
                with open('./media/temp/{}'.format(request.FILES['image'].name), 'wb+') as destination:
                    for chunk in request.FILES['image'].chunks():
                        destination.write(chunk)
            if request.FILES.get('attached_file'):
                os.makedirs('./media/temp/', exist_ok=True)

templates/qna/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ question.title }} | 도와줘, 코딩
{% endblock %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock css %}

{% load hitcount_tags %}

{% block js %}
<script type="text/javascript" src="/static/js/qna_detail.js" defer></script>
{% endblock %}

{% block content %}
{{ request.user.id|json_script:"user_id" }}
{{ question.id|json_script:"question_id" }}
<main>
    <h1>{{ question.title }}</h1>
    <div style="display: flex; justify-content: space-between;">
        <!-- js 에서 question info를 split 하는데, 한 줄에 안 쓰면 공백이 들어가므로 한 줄로 써야 함 -->
        <p class = "question__info ">{{ question.created_at|date:'y.m.d'}} · 조회 {% get_hit_count for question %} · 좋아요 {{ total_likes }} · <a href="{% if question.user %}{% url 'user:public_userpage' question.user.pk %}{% endif %}" style="text-decoration: none; color:#212529;">{{ username }}</a></p>
        <p>
            {% if question.user.id == user.id and user.is_authenticated %}
            <a href="{% url 'qna:question_update' question.pk %}" class="question__edit-btn">수정</a>
                {% if answers_count > 0 %}
                <a class="question__delete-btn" onclick="alert('답변이 달려 있어서 삭제할 수 없어요🥺')">삭제</a>      
                {% else %}
                <span class="question__delete-btn question__delete-btn--actual">삭제</span>      
                {% endif %}
            {% endif %}
        </p>
    </div>
    <div class="question__detail__tagcontainer">
        {% if question.s_or_e_tag == 'S' %}
        <a href="{% url 'qna:question_list' %}?tag_filter_by=S">
            <div class="question__detail__tag question__detail__scratchtag">스크래치</div>
        </a>
        {% elif question.s_or_e_tag == 'E' %}
        <a href="{% url 'qna:question_list' %}?tag_filter_by=E">
            <div class="question__detail__tag question__detail__entrytag">엔트리</div>
        </a>
        {% else %}
        <a href="{% url 'qna:question_list' %}?tag_filter_by=ETC">
            <div class="question__detail__tag question__detail__etctag">기타</div>
        </a>
        {% endif %}
        
        {% for tag in tags %}
        <a href="{% url 'qna:search_result' %}?search={{ tag.tag_name }}">
            <div class="question__detail__tag">
                {{ tag.tag_name }}
            </div>
        </a>
        {% endfor %}
    </div>
    <hr>
    <div class="question__detail__content">
        <p>{{ question.content }}</p>
        
        {% if question.image %}<img src="{{ question.image.url }}">{% endif %}
        
        {% if question.attached_file %}
        <div class="detail__content--attached_file">
            <div class="attached_file--left">
                <label>첨부파일</label>
                <div>{{ question.get_filename }}</div>
            </div>
            <form action="{% url 'qna:download' question.id %}">
                <button type="submit">
                    다운로드
                </button>
            </form>
        </div>
        {% endif %}
        <div class="question__like-btn">
            {% if is_liked %}
            <i class="fas fa-heart"></i>
            {% else %}
            <i class="far fa-heart"></i>
            {% endif %}
            <span>{{ total_likes }}</span>
        </div>
    </div>
        
    <hr>

    <div class="question__buttons">
        <a href="{% url 'qna:question_list' %}" class="question__list-btn">목록보기</a>
        {% if previous_pk != -1 %}
        <span style="color: #828282;"> · </span>
        <a href="{% url 'qna:question_detail' previous_pk %}" class="question__prev-btn">이전글</a>
        {% endif %}
        {% if next_pk != -1 %}
        <span style="color: #828282;"> · </span>
        <a href="{% url 'qna:question_detail' next_pk %}" class="question__next-btn">다음글</a>
        {% endif %}
    </div>
    <hr>
    
    
    <div class="answer__input__container">
        <textarea name="new_answer" placeholder="답변을 입력하세요" class="answer__input";></textarea>  
        <input type="button" value = "등록" class="answer__submit">
    </div>

    <p class="answer__total-count" style="font-weight: bold; font-size: 18px; line-height: 150%; color: black;">답변 {{ answers_count }} 개 </p>

    <div class="answer__list">
        <!-- 답변 부분 -->
        {% for answer, replies in answers_reply_dict.items %}
            <div class="answer__container answer__container--{{ answer.id }}" id="answer-id-{{ answer.id }}">
                <div class="answer__content-container answer__content-container--{{ answer.id }}">
                    <div class="answer__user__profile">
                        <div class="answer__user__profile-left">
                            {% if answer.user.img %}
                            <img src= '{{ answer.user.img.url }}'>
                            {% elif answer.user.default_img %}
                            <img src="/static/img/user_thumbnail/{{ answer.user.default_img }}">
                            {% endif %}
                        </div>
                        <div class="answer__user__profile-right">
                            <div> <!-- 이름, 글쓴이, 날짜 -->
                                <div class="answer__user__name answer__user__name--{{ answer.id }}">
                                    {% if answer.user %}
                                    <h2><a href="{% url 'user:public_userpage' answer.user.pk %}" style="text-decoration: none; color:#212529;">{{ answer.user }}</a></h2>
                                    {% if answer.user.id == question.user.id %}
                                    <span class="answer__writer-mark">글쓴이</span>
                                    {% endif %}
                                    {% else %}
                                    <h2>(알 수 없음)</h2>
                                    {% endif %}
                                </div>
                                <p>{{ answer.created_at|date:'y.m.d  H:i'}}</p>
                            </div>
                            {% if answer.user.id == user.id %}
                            <div>
                                <button class="answer__edit-btn answer__edit-btn--{{ answer.id }} " id="answer-edit-btn-{{ answer.id }}">수정</button>
                                <button class="answer__delete-btn answer__delete-btn--{{ answer.id }} " id="answer-delete-btn-{{ answer.id }}">삭제</button>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <p class="answer__content answer__content--{{ answer.id }}">{{ answer.content }}</p>
                    <div class="answer__like__reply">
                        <div>
                            <input type="checkbox" class="answer__write-reply answer__write-reply--{{ answer.id }} btn-check " id="reply-btn-{{ answer.id }}" autocomplete="off">
                            <label class="answer__reply-btn" for="reply-btn-{{ answer.id }}">답글 작성</label>
                        </div>
                        <div class="answer__like-btn answer__like-btn--{{ answer.id }}"  id="answer-like-{{ answer.id }}">
                            {% if user in answer.like_user.all %}
                            <i class="fas fa-heart"></i>
                            {% else %}
                            <i class="far fa-heart"></i>
                            {% endif %}
                            <span>{{ answer.like_user.all | length }}</span>
                        </div>
                    </div>
                </div>

                <div class="answer__edit answer__edit--{{ answer.id }}" style=" display: none;">
                    <div class="answer__edit__flexbox">
                        <textarea name="edit_answer_{{ answer.id }}" class="answer__edit-input answer__edit-input--{{ answer.id }}" id = "answer-edit-input-{{ answer.id }}" value="{{ answer.content }}"></textarea>
                        <input type="button" value = "수정" class="answer__edit-submit answer__edit-submit--{{ answer.id }}" id = "answer-edit-submit-{{ answer.id }}">
                    </div>
                </div>

                <div class="reply__list reply__list--{{ answer.id }} ">
                    <!-- 대댓글 부분 -->
                    {% for reply in replies %}
                        <div class="reply__container reply__container--{{reply.id}} answer__container--{{ reply.id }} ">
                            <div class="answer__content-container answer__content-container--{{ reply.id }}">
                                <div class="answer__user__profile">
                                    <div class="answer__user__profile-left">
                                        {% if reply.user.img %}
                                        <img src= '{{ reply.user.img.url }}'>
                                        {% elif reply.user.default_img %}
                                        <img src="/static/img/user_thumbnail/{{ reply.user.default_img }}">
                                        {% endif %}
                                    </div>
                                    <div class="answer__user__profile-right">
                                        <div>
                                            <div class="answer__user__profile-name">
                                                {% if reply.user %}
                                                <h2><a href="{% url 'user:public_userpage' reply.user.pk %}" style="text-decoration: none; color:#212529;">{{ reply.user }}</a></h2>
                                                {% if reply.user.id == question.user.id %}
                                                <span class="answer__writer-mark">글쓴이</span>
                                                {% endif %}
                                                {% else %}
                                                <h2>(알 수 없음)</h2>
                                                {% endif %}
                                            </div>
                                            <p>{{ reply.created_at|date:'y.m.d  H:i' }}</p>
                                        </div>
                                        {% if reply.user.id == user.id %}
                                        <div>
                                            <button class="answer__edit-btn answer__edit-btn--{{ reply.id }} " id="answer-edit-btn-{{ reply.id }}">수정</button>
                                            <button class="answer__delete-btn answer__delete-btn--{{ reply.id }} " id="answer-delete-btn-{{ reply.id }}">삭제</button>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <p class= "answer__content answer__content--{{ reply.id }}">{{ reply.content }}</p>
                                <div class="answer__like-btn answer__like-btn--{{ reply.id }}" id="reply-like-{{ reply.id }}" style="align-self:flex-end">
                                    {% if user in reply.like_user.all %}
                                    <i class="fas fa-heart"></i>
                                    {% else %}
                                    <i class="far fa-heart"></i>
                                    {% endif %}
                                    <span>{{ reply.like_user.all | length }}</span>
                                </div>

                            </div>

                            <div class="answer__edit answer__edit--{{ reply.id }}" style=" display: none;">
                                <div class="answer__edit__flexbox">
                                    <input type="text" name="edit_answer_{{ reply.id }}" class="answer__edit-input answer__edit-input--{{ reply.id }}" id = "answer-edit-input-{{ reply.id }}" 
                                    value="{{ reply.content }}">    
                                    <input type="button" value = "수정" class="answer__edit-submit answer__edit-submit--{{ reply.id }}" id = "answer-edit-submit-{{ reply.id }}">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="reply__form reply__form--{{ answer.id }}" style="display: none;">
                    <div class="reply__form__flexbox">
                        {% if user.is_authenticated %}
                        <textarea name="new_reply_{{ answer.id }}" placeholder="답변을 입력하세요" class="reply__input reply__input--{{ answer.id }}" id = "reply-input-{{ answer.id }}"></textarea>
                        <input type="button" value = "작성" class="reply__submit reply__submit--{{ answer.id }}" id = "reply-submit-{{ answer.id }}">
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


</main>
{% endblock %}