config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (handler404, handler500)

handler404 = 'common.views.page_not_found'
handler500 = 'common.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('group/', include('group.urls')),
    path('', include('user.urls')),
    path('qna/', include('qna.urls')),
    # path('account/', include('allauth.urls')), #account.urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/urls.py
from django.urls import path
from . import views
from .views import FileDownloadView

app_name = 'group'

urlpatterns = [
    path('', view=views.group_home, name='group_home'),
    path('group_search_public/', view=views.group_search_public, name='group_search_public'),
    path('group_create/', view=views.group_create, name='group_create'),
    path('<int:pk>/group_update/', view=views.group_update, name='group_update'),
    path('<int:pk>/group_delete/', view=views.group_delete, name='group_delete'),
    path('<int:pk>/group_drop/', view=views.group_drop, name='group_drop'),
    path('<int:pk>/group_detail/', view=views.group_detail, name='group_detail' ),
    path('group_list/', view=views.group_list, name='group_list'),
    path('<int:pk>/public_group_join/', view=views.public_group_join, name='public_group_join'),
    path('<int:pk>/group_wait_cancel/', view=views.group_wait_cancel, name='group_wait_cancel'),
    path('interest_ajax/', view=views.interest_ajax, name='interest_ajax'),
    path('join_code_ajax/', view=views.join_code_ajax, name='join_code_ajax'),
    path('create_code_ajax/', view=views.create_code_ajax, name='create_code_ajax'),
    path('wait_list_ajax/', view=views.wait_list_ajax, name='wait_list_ajax'),
    path('group_star_ajax/', view=views.group_star_ajax, name='group_star_ajax'),
    path('group_join_accept/', view=views.group_join_accept, name='group_join_accept'),
    path('group_join_reject/', view=views.group_join_reject, name='group_join_reject'),
    path('group_member_state/', view=views.group_member_state, name='group_member_state'),
    # path('<int:pk>/member_thumbnail/', view=views.member_thumbnail, name='member_thumbnail'),
    #### 게시판 관련 url
    path('<int:pk>/post_list/', view=views.post_list, name='post_list'),
    path('<int:pk>/post_create/', view=views.post_create, name='post_create'),
    path('<int:pk>/post_update/<int:post_pk>', view=views.post_update, name='post_update'),
    path('<int:pk>/post_delete/<int:post_pk>', view=views.post_delete, name='post_delete'),
    path('<int:group_pk>/post_detail/<int:pk>', view=views.GroupPostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/search_list/', view=views.search_result, name='search_result'),
    path('answer_ajax/', view=views.answer_ajax, name='answer_ajax'),
    path('reply_ajax/', view=views.reply_ajax, name='reply_ajax'),
    path('post_like_ajax/', view=views.post_like_ajax, name='post_like_ajax'),
    path('answer_like_ajax/', view=views.answer_like_ajax, name='answer_like_ajax'),
    path('answer_delete_ajax/', view=views.answer_delete_ajax, name='answer_delete_ajax'),
    path('answer_edit_ajax/', view=views.answer_edit_ajax, name='answer_edit_ajax'),
    path('answer_edit_submit_ajax/', view=views.answer_edit_submit_ajax, name='answer_edit_submit_ajax'),
    path('<int:pk>/download/', FileDownloadView.as_view(), name="download"),
]

qna/urls.py
from django.urls import path
from . import views
from .views import FileDownloadView

app_name = 'qna'

urlpatterns = [
    #path('',views.QuestionView.as_view(), name='question_list'),
    path('',views.question_list, name='question_list'),
    path('search_result/', views.search_result, name='search_result'),
    path('question_create/', views.question_create, name='question_create'),
    #path('question_create/', views.FileFieldFormView.as_view(), name='question_create'),
    #path('<int:pk>/', views.question_detail, name='question_detail'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('<int:pk>/update', views.question_update, name='question_update'),
    path('<int:pk>/delete', views.question_delete, name='question_delete'),
    path('answer_ajax/', views.answer_ajax, name='answer_ajax'),
    path('reply_ajax/', views.reply_ajax, name='reply_ajax'),
    path('question_like_ajax/', views.question_like_ajax, name='question_like_ajax'),
    path('answer_like_ajax/', views.answer_like_ajax, name='answer_like_ajax'),
    path('answer_delete_ajax/', views.answer_delete_ajax, name='answer_delete_ajax'),
    path('answer_edit_ajax/', views.answer_edit_ajax, name='answer_edit_ajax'),
    path('answer_edit_submit_ajax/', views.answer_edit_submit_ajax, name='answer_edit_submit_ajax'),
    path('<int:pk>/download/', FileDownloadView.as_view(), name="download"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.main, name="main"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.log_out, name="logout"),
    path('signup/', views.sign_up, name="signup"),
    path('activate/<uid64>/<token>/', views.activate, name="activate"),
    path('mypage/', views.my_page, name="mypage"),
    path('mypage/revise/', views.my_page_revise, name="mypage_revise"),
    path('mypage/question/',
         views.QuestionView.as_view(), name="mypage_question"),
    path('mypage/answer/', views.AnswerView.as_view(), name="mypage_answer"),
    path('mypage/reward/<int:pk>/', views.my_page_reward, name="mypage_reward"),
    path('mypage/reward/representative_ajax/',
         views.representative_reward_ajax, name="representative_reward_ajax"),
    path('mypage/reward/date_ajax/',
         views.date_reward_ajax, name="date_reward_ajax"),
    path('mypage/point/', views.PointView.as_view(), name="mypage_point"),
    path('mypage/alert/', views.AlertView.as_view(), name="mypage_alert"),
    path('mypage/alert/check_ajax/',
         views.check_alert_ajax, name="check_alert_ajax"),
    path('mypage/alert/check_all_ajax/',
         views.check_all_alert_ajax, name="check_all_alert_ajax"),
    path('mypage/alert/load_new_ajax/',
         views.load_new_alert_ajax, name="load_new_alert_ajax"),
    path('<int:pk>/public_userpage/',
         views.public_userpage, name='public_userpage'),
    path('<int:pk>/public_userpage/question/',
         views.QuestionView.as_view(), name="public_userpage_question"),
    path('<int:pk>/public_userpage/answer/',
         views.AnswerView.as_view(), name="public_userpage_answer"),
    path('<int:pk>/public_userpage/reward/',
         views.my_page_reward, name="public_userpage_reward"),
    path('group_wait_profile/', view=views.group_wait_profile,
         name='group_wait_profile'),
    path('drop/', views.drop, name="drop"),
    path('drop_success/', views.drop_success, name="drop_success"),
    path('periodic_tasks/', views.periodic_tasks, name="periodic_tasks"),
    path('periodic_tasks_immediate/', views.periodic_tasks_immediate,
         name="periodic_tasks_immediate"),
    path('initialize_rewards/', views.initialize_rewards,
         name="initialize_rewards"),
    path('password_change/search/',
         views.password_change_search, name="password_change_search"),
    path('password_change/<uid64>/<token>/',
         views.password_change, name="password_change"),
]

group/forms.py
from django import forms
from .models import *

class GroupForm(forms.ModelForm):
    img_recent = forms.CharField(required=False)
    class Meta:
        model = Group
        fields = ('name', 'image', 'intro')

class PostForm(forms.ModelForm):
    img_recent = forms.CharField(required=False)
    file_recent = forms.CharField(required=False)
    class Meta:
        model = GroupPost
        exclude = ('hit', 'user', 'group')

group/views.py
from calendar import c
from email import message
import re
from tkinter import E
from tokenize import blank_re
import uuid
import base64
import codecs
import json
import shutil
import os
import mimetypes
import time
from django.shortcuts import render, redirect, get_object_or_404
from django.templatetags.static import static
from django.db.models import Q, F
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import JsonResponse, FileResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from .models import *
from .forms import *
from django.core.paginator import Paginator
from hitcount.views import HitCountDetailView
from django.views.generic import ListView, View
from django.views.generic.detail import SingleObjectMixin
from django.core.files.storage import FileSystemStorage
from config.settings import MEDIA_ROOT
from user.update import *
from .iframe import *
from threading import Timer
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AnonymousUser


######## 그룹 메인 페이지 ########

# 나의 그룹


def group_home(request):

    user = request.user  # 현재 접속한 사용자

    if user == AnonymousUser():
        return redirect('user:main')
    # 해당 유저의 그룹 리스트
    groups = user.group_set.all()
    group_star = Group.objects.filter(star_group__user=user)
    # group_star = GroupStar.objects.filter(group=groups)

    # 정렬하기
    sort_by = request.GET.get('sort', 'star')
    if sort_by == 'name':
        groups = groups.order_by('name', '-id')
    elif sort_by == 'star':  # filter -> 정렬
        dict = {}
        for group in groups:
            dict[group] = group.star_group.filter(user=user).count()
        groups = sorted(groups, key=lambda group: dict[group], reverse=True)

    # for group_star in groups:
    #     if is_star = 'True':
    #         groups_star_dict[group_star] = is_star

    # 페이징 처리
    page = request.GET.get('page', '1')

    # user의 닉네임이랑 같은 경우에 처리해야 하는 부분 이후 추가
    pagintor = Paginator(groups, 6)
    page_obj = pagintor.get_page(page)

    groups_star_dict = {}
    for group in page_obj:
        if group in group_star:
            groups_star_dict[group] = True
        else:
            groups_star_dict[group] = False

    ctx = {
        'user': user,  # 나중에는 쓸모 X
        'groups': page_obj,
        'groups_star_dict': groups_star_dict,
        'sort_by': sort_by,
        'ani_image': static('img/group_default.png'),
        'code_ex': static('image/code_ex.jpg')
    }

    return render(request, template_name='group/group_home.html', context=ctx)


# 그룹 검색하기(공개 그룹 찾기)
def group_search_public(request):
    user = request.user
    if user == AnonymousUser():
        return redirect('user:main')
    groups = Group.objects.all()

    if not request.GET.get('search') or request.GET.get('search').isspace():
        return redirect('group:group_list')

    if 'search' in request.GET:
        query = request.GET.get('search')
        groups = groups.filter(Q(name__icontains=query) & Q(mode='PUBLIC'))

    sort_by = request.GET.get('sort', 'interest')
    if sort_by == 'name':
        groups = groups.order_by('name')
    elif sort_by == 'interest':
        groups = groups.annotate(total_likes=Count(
            'interests')).order_by('-total_likes')
    elif sort_by == 'member':
        groups = groups.annotate(total_members=Count(
            'members')).order_by('-total_members')

    # 페이징 처리
    page = request.GET.get('page', '1')
    paginator = Paginator(groups, 1)    # 페이지당 6개씩 보여주기
    page_obj = paginator.get_page(page)

    ctx = {
        'groups': page_obj,
        'query': query,
        'ani_image': static('img/group_default.png'),
        'sort_by': sort_by,
    }

    return render(request, 'group/group_search_public.html', context=ctx)


######## 그룹 CRUD ########

# 그룹 생성
def group_create(request):
    user = request.user
    if user == AnonymousUser():
        return redirect('user:main')

    user = request.user

    if request.method == 'POST':
        form = GroupForm(request.POST, request.FILES)

        name = request.POST.get('name')
        image = request.FILES.get('image')
        mode = request.POST.get('group-mode__tag')

        # 에러 메세지
        error = GroupErrorMessage()
        error.validation_group(name, mode, '', 'group_create')

        if not error.has_error_group() and form.is_valid():
            #group = form.save()
            group=Group.objects.create(
                name=name,
                mode=mode,
                intro=request.POST.get('intro'),
            )
            os.makedirs(
                MEDIA_ROOT + '/group/group_{}/thumbnail/'.format(group.pk), exist_ok=True)
            group.mode = mode
            group.maker = user    # 방장 = 접속한 유저
            group.members.add(user)  # 방장도 그룹의 멤버로 추가

            if request.FILES.get('image'):  # form valid + 이미지 첨부 시
                group.image = request.FILES.get('image')
                # group.image = './group/group_{}/thumbnail/{}'.format(
                #   group.pk, request.FILES['image'].name)
            elif request.POST['img_recent']:
                os.makedirs(MEDIA_ROOT + '/temp/', exist_ok=True)
                shutil.copyfile('./media/temp/{}'.format(request.POST['img_recent']),
                                './media/group/group_{}/thumbnail/{}'.format(group.pk, request.POST['img_recent']))
                group.image = './group/group_{}/thumbnail/{}'.format(
                    group.pk, request.POST['img_recent'])
                # temp 파일 삭제
                if os.path.isfile('./media/temp/{}'.format(request.POST['img_recent'])):
                    os.remove(
                        './media/temp/{}'.format(request.POST['img_recent']))
            group.save()
            update_group_create(group, user)

            return redirect('group:group_home')

        original_info = OriginalGroupInfo()
        original_info.remember(request)
        # 다른 필드 에러 시(기존 파일 남아있도록)
        if request.FILES.get('image'):
            os.makedirs(MEDIA_ROOT + '/temp/', exist_ok=True)
            with open('./media/temp/{}'.format(request.FILES.get('image')), 'wb+') as destination:
                for chunk in request.FILES['image'].chunks():
                    destination.write(chunk)

        original_info.image = request.POST['img_recent']

        ctx = {
            'error': error,
            'origin': original_info,
            'temp_img_location': '/media/temp/'
        }

        return render(request, template_name='group/group_form.html', context=ctx)

    else:
        form = GroupForm()
        users = User.objects.all()
        # users = User.objects.exclude(user)
        # form.fields['maker'].queryset = users
        ctx = {'form': form, 'temp_img_location': '/media/temp/'}

        return render(request, 'group/group_form.html', context=ctx)

# 그룹 정보 수정


def group_update(request, pk):
    user = request.user
    if user == AnonymousUser():
        return redirect('user:main')

    group = get_object_or_404(Group, pk=pk)
    members = group.members.all()
    prev_name = group.name

    if (user not in members) or (user != group.maker):
        return redirect('group:group_home')

    if request.method == 'POST':
        form = GroupForm(request.POST, request.FILES, instance=group)

        # group.name = request.POST.get('name')
        # name = group.name
        name = request.POST.get('name')
        intro = request.POST.get('intro')
        mode = request.POST.get('group-mode__tag')

        # group.intro = request.POST.get('intro')
        # intro = group.intro

        # mode = request.POST.get('group-mode__tag')
        # group.mode = mode

        
        # 에러 메세지
        error = GroupErrorMessage()
        error.validation_group(name, mode, prev_name, 'group_update')

        if not error.has_error_group() and form.is_valid():
            group = form.save()
            group.name = name
            group.intro = intro
            group.mode = mode

            if request.FILES.get('image'):  # form valid 시
                group.image = request.FILES.get('image')

            elif request.POST['img_recent']:   # 다른 필드 에러 시(기존 파일 남아있도록)
                if os.path.isfile('./media/group/group_{}/thumbnail/{}'.format(group.pk, request.POST['img_recent'])):
                    group.image = './group/group_{}/thumbnail/{}'.format(group.pk, request.POST['img_recent'])
                else:
                    os.makedirs(MEDIA_ROOT + '/temp/', exist_ok=True)
                    shutil.copyfile('./media/temp/{}'.format(request.POST['img_recent']),
                               './media/group/group_{}/thumbnail/{}'.format(group.pk, request.POST['img_recent'])) ###
                    group.image = './group/group_{}/thumbnail/{}'.format(group.pk, request.POST['img_recent'])
                    # temp 파일 삭제
                if os.path.isfile('./media/temp/{}'.format(request.POST['img_recent'])):
                    os.remove('./media/temp/{}'.format(request.POST['img_recent']))
                # group.image = './group/group_{}/thumbnail/{}'.format(
                #     group.pk, request.POST['img_recent'])
                # # original_info.image = request.POST['img_recent']

            group.save()

            return redirect('group:group_detail', pk)

        # 에러 메세지가 존재할 때
        else:
            if request.FILES.get('image'):
                os.makedirs(MEDIA_ROOT + '/temp/', exist_ok=True)
                with open('./media/temp/{}'.format(request.FILES['image'].name), 'wb+') as destination:
                    for chunk in request.FILES['image'].chunks():
                        destination.write(chunk)

            original_info = OriginalGroupInfo()
            original_info.remember(request)

            original_info.image = request.POST['img_recent']

            if group.image:

templates/group/group_member_state.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block content %}
<div class="group__user__join-state">
    <div class="group__user--name">{{ user.nickname }}</div>
    <div class="group__join__list">
        {% for group in groups %}
            <div class="group__wait__container d-flex flex-row">
                <div>{{ group.name }}</div>
                <div>{{ wait_status }}</div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/group/search_result.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load my_tags %}

{% block js %}
<script type="text/javascript" src="/static/js/group_post_list.js" defer></script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/group_post_search_result.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}" />
{% endblock %}

{% block title %} 도와줘, 코딩 | {{ group.name }} | 검색 결과 {% endblock %}

{% block content %}

<div class="group-post__top">   <!-- 게시판 상단 -->
    <div class="group-post__top-left">
        <a href="{% url 'group:post_list' group.pk %}" class="group-post__top--title">{{ group.name }}</a>
        <div class="group-post__top--intro">{{ group.intro }}</div>
    </div>
    <div class="group-post__top--info">
        <a href="{% url 'group:group_detail' group.pk %}">그룹 정보</a>
    </div>
</div>

<div class="qna-sort-filter__box">
    <!-- 최신순 조회수순 좋아요순 -->
    <div class="list-sort">
        <span class="list-sort__btn">
            {% if sort_by != 'recent' %}
            <a href="{% url 'group:search_result' group.pk %}?{% param_replace sort='recent' page=1 search=query %}">최신순</a>
            {% else %}
            <span>최신순</span>
            {% endif %}
        </span>
        <span class="list-sort__btn">
            {% if sort_by != 'view' %}
            <a href="{% url 'group:search_result' group.pk %}?{% param_replace sort='view' page=1 search=query %}">조회수순</a>
            {% else %}
            <span>조회수순</span>
            {% endif %}
        </span>
        <span class="list-sort__btn">
            {% if sort_by != 'liked' %}
            <a href="{% url 'group:search_result' group.pk %}?{% param_replace sort='liked' page=1 search=query %}">좋아요순</a>
            {% else %}
            <span>좋아요순</span>
            {% endif %}
        </span>
    </div>
</div>

<div class="group-post__list">  <!-- 게시글 목록 시작 -->
    <div class="search-result__top">
        <div class="search--result__query">
            <span class="search-result__top--query">{{ query }}</span>
            <span class="search-result__top--text">에 대한 검색 결과</span>
        </div>
    </div>

    <div class="gridbox"> 
        {% for post, answer_count in posts_answer_count_dict.items %}
        <div class="gridbox__item-post">    <!-- 그룹 게시글 하나 시작 -->
            <a href="{% url 'group:post_detail' group.pk post.pk %}"> 
                <div class="img__post">
                    {% if post.thumbnail_url %}
                    <img alt="" src="{{ post.thumbnail_url }}" height="200" width="200" class="img__post-img">
                    {% else %}
                    <img src="/static/img/none_image_group_post.png" height="200" width="200" class="img__post-img" />
                    {% endif %}
                </div>

                <div class="group_post-tag">   <!-- 게시글 태그 수정 여기서 해주세요 -->
                    {% if post.category == 'S' %}
                    <span class="post-tag">자랑</span>
                    {% elif post.category == 'Q' %}
                    <span class="post-tag">질문</span>
                    {% else %}
                    <span class="post-tag">기타</span>
                    {% endif %}
                </div>

                <div class="comment__post">   <!-- 댓글 개수 -->
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path d="M13.1592 0.505859H1.90918C0.875 0.505859 0.0341797 1.34668 0.0341797 2.38086V10.8184C0.0341797 11.8525 0.875 12.6934 1.90918 12.6934H4.72168V15.1543C4.72168 15.4414 5.0498 15.6084 5.28125 15.4385L8.94043 12.6934H13.1592C14.1934 12.6934 15.0342 11.8525 15.0342 10.8184V2.38086C15.0342 1.34668 14.1934 0.505859 13.1592 0.505859Z" fill="white"/>
                    </svg>
                    <span>{{ answer_count }}</span>    <!-- 댓글 개수 수정 여기서 해주세요 -->
                </div>

                <div class="content__post">
                    <!-- 그룹 이름 -->
                    <div class="content__post-titlebox">
                        <!-- 그룹 게시글 디테일 페이지로 이동 (후에 수정 필요) -->
                        <span class="post-title content__post-title">{{ post.title }}</span>
                    </div>
                    <!-- 작품 소개글 -->
                    <div class="content__post-intro">
                        <span class="post-intro">{{ post.content }}</span>
                    </div>
                    <!-- 글 정보 -->
                    <div class="content__post-info">
                        <span class="post-info">{{ post.created_at | date:'y.m.d' }} · {{ post.user }} · 조회  {% get_hit_count for post %} · 좋아요 {{ post.like_user.all | length }}</span>
                    </div>
                </div>
            </a>
        </div>  <!-- 그룹 게시글 하나 끝 -->
        <!-- 검색 결과가 없으면 -->
        {% empty %}
        <div></div>
        <div class="search-result__notresult">
            <span class="notresult-query">{{ query }}<br/>
            <span class="notresult-text">글을 찾을 수 없어요🥺</span><br/>
            <span class="notresult-text">다른 글을 찾아보세요!</span><br/>
        </div>
        <div></div>        
    </div>
    {% endfor %}
</div>  <!-- 게시글 목록 끝 -->

<div class="group_post__search-container">  <!-- 게시글 검색 -->
    {% if is_member %}
    <a class="group_post__ask-btn" href="{% url 'group:post_create' group.pk %}">내 작품 공유</a>
    {% else %}
    <span class="group_post__ask-btn" onclick="alert('그룹에 가입 후 이용해주세요. 😄')">내 작품 공유</span>
    {% endif %}
    <form class="group_post__search-box" action="{% url 'group:search_result' group.pk %}" method="get">
        {% csrf_token %}
        <input type="search" placeholder="작품을 검색해보세요!" name="search" class="group_post__search__input"/>
        <button type="submit" class="group_post__search__submit">
            <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M25.1504 22.115L20.2822 17.2468C20.0625 17.0271 19.7646 16.905 19.4521 16.905H18.6562C20.0039 15.1814 20.8047 13.0134 20.8047 10.655C20.8047 5.04468 16.2588 0.498779 10.6484 0.498779C5.03809 0.498779 0.492188 5.04468 0.492188 10.655C0.492188 16.2654 5.03809 20.8113 10.6484 20.8113C13.0068 20.8113 15.1748 20.0105 16.8984 18.6628V19.4587C16.8984 19.7712 17.0205 20.0691 17.2402 20.2888L22.1084 25.157C22.5674 25.616 23.3096 25.616 23.7637 25.157L25.1455 23.7751C25.6045 23.3162 25.6045 22.574 25.1504 22.115ZM10.6484 16.905C7.19629 16.905 4.39844 14.1121 4.39844 10.655C4.39844 7.20288 7.19141 4.40503 10.6484 4.40503C14.1006 4.40503 16.8984 7.198 16.8984 10.655C16.8984 14.1072 14.1055 16.905 10.6484 16.905Z" fill="#4E4E4E"/>
            </svg>
            </button>
    </form> 
</div>


<!-- 페이지네이션 -->
<div class="pagination-box">
    <ul class="all__pagination">
        {% if posts.has_previous %}
        <li class="all__page-item">
            <a class="all__page-sign" href="?{% param_replace page=posts.previous_page_number search=query %}">
                <!-- 이전페이지 -->
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
                <path d="M12.7688 22.5918L2.02827 11.8513L12.7688 1.11076" stroke="#C4C4C4" stroke-width="2"/>
                </svg>
            </a>
        </li>
        {% else %}
        <li class="all__page-item">
            <a class="all__page-sign" href="#">
                <!-- 이전페이지 -->
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
                <path d="M12.7688 22.5918L2.02827 11.8513L12.7688 1.11076" stroke="#C4C4C4" stroke-width="2"/>
                </svg>
            </a>
        </li>
        {% endif %}

        {% if posts.number|add:'-2' > 1 and posts.paginator.num_pages > 5 %}
        <li class="all__page-item">
            <a class="all__page-link" href="?{% param_replace page=posts.number|add:'-5' search=query %}">
                ...
            </a>
        </li>
        {% endif %}

        {% for page_number in posts.paginator.page_range %}
            {% if page_number == posts.number %}
            <li class="all__page-item">
                <a class="all__page-item-active" href="?{% param_replace page=page_number search=query %}">{{ page_number }}</a>
            </li>
            {% else %}
                {% if posts.number < 4 %}
                    {% if page_number < 6 %}
                        <li class="all__page-item">
                            <a class="all__page-link" href="?{% param_replace page=page_number search=query %}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% elif posts.number > posts.paginator.num_pages|add:'-2' %}
                    {% if page_number > posts.paginator.num_pages|add:'-5' %}
                        <li class="all__page-item">
                            <a class="all__page-link" href="?{% param_replace page=page_number search=query %}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% else %}
                    {% if page_number > posts.number|add:'-3' and page_number < posts.number|add:'3' %}
                        <li class="all__page-item">
                            <a class="all__page-link" href="?{% param_replace page=page_number search=query %}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endfor %}

        {% if posts.paginator.num_pages > posts.number|add:'2' and posts.paginator.num_pages > 5 %}
        <li class="all__page-item">
            <a class="all__page-link" href="?{% param_replace page=posts.number|add:'5' search=query %}">
                ...
            </a>
        </li>
        {% endif %}

        {% if posts.has_next %}
        <li class="all__page-item">
            <a class="all__page-sign sign-next" href="?{% param_replace page=posts.next_page_number search=query %}">
                <!-- 다음페이지 -->
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
                <path d="M1.23096 1.11035L11.9715 11.8509L1.23096 22.5914" stroke="#C4C4C4" stroke-width="2"/>
                </svg>
            </a>
        </li>
        {% else %}
        <li class="all__page-item">
            <a class="all__page-sign sign-next" href="#">
                <!-- 다음페이지 -->
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
                <path d="M1.23096 1.11035L11.9715 11.8509L1.23096 22.5914" stroke="#C4C4C4" stroke-width="2"/>
                </svg>
            </a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}