config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (handler404, handler500)

handler404 = 'common.views.page_not_found'
handler500 = 'common.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('group/', include('group.urls')),
    path('', include('user.urls')),
    path('qna/', include('qna.urls')),
    # path('account/', include('allauth.urls')), #account.urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path
from . import views
from .views import FileDownloadView

app_name = 'qna'

urlpatterns = [
    #path('',views.QuestionView.as_view(), name='question_list'),
    path('',views.question_list, name='question_list'),
    path('search_result/', views.search_result, name='search_result'),
    path('question_create/', views.question_create, name='question_create'),
    #path('question_create/', views.FileFieldFormView.as_view(), name='question_create'),
    #path('<int:pk>/', views.question_detail, name='question_detail'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('<int:pk>/update', views.question_update, name='question_update'),
    path('<int:pk>/delete', views.question_delete, name='question_delete'),
    path('answer_ajax/', views.answer_ajax, name='answer_ajax'),
    path('reply_ajax/', views.reply_ajax, name='reply_ajax'),
    path('question_like_ajax/', views.question_like_ajax, name='question_like_ajax'),
    path('answer_like_ajax/', views.answer_like_ajax, name='answer_like_ajax'),
    path('answer_delete_ajax/', views.answer_delete_ajax, name='answer_delete_ajax'),
    path('answer_edit_ajax/', views.answer_edit_ajax, name='answer_edit_ajax'),
    path('answer_edit_submit_ajax/', views.answer_edit_submit_ajax, name='answer_edit_submit_ajax'),
    path('<int:pk>/download/', FileDownloadView.as_view(), name="download"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.main, name="main"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.log_out, name="logout"),
    path('signup/', views.sign_up, name="signup"),
    path('activate/<uid64>/<token>/', views.activate, name="activate"),
    path('mypage/', views.my_page, name="mypage"),
    path('mypage/revise/', views.my_page_revise, name="mypage_revise"),
    path('mypage/question/',
         views.QuestionView.as_view(), name="mypage_question"),
    path('mypage/answer/', views.AnswerView.as_view(), name="mypage_answer"),
    path('mypage/reward/<int:pk>/', views.my_page_reward, name="mypage_reward"),
    path('mypage/reward/representative_ajax/',
         views.representative_reward_ajax, name="representative_reward_ajax"),
    path('mypage/reward/date_ajax/',
         views.date_reward_ajax, name="date_reward_ajax"),
    path('mypage/point/', views.PointView.as_view(), name="mypage_point"),
    path('mypage/alert/', views.AlertView.as_view(), name="mypage_alert"),
    path('mypage/alert/check_ajax/',
         views.check_alert_ajax, name="check_alert_ajax"),
    path('mypage/alert/check_all_ajax/',
         views.check_all_alert_ajax, name="check_all_alert_ajax"),
    path('mypage/alert/load_new_ajax/',
         views.load_new_alert_ajax, name="load_new_alert_ajax"),
    path('<int:pk>/public_userpage/',
         views.public_userpage, name='public_userpage'),
    path('<int:pk>/public_userpage/question/',
         views.QuestionView.as_view(), name="public_userpage_question"),
    path('<int:pk>/public_userpage/answer/',
         views.AnswerView.as_view(), name="public_userpage_answer"),
    path('<int:pk>/public_userpage/reward/',
         views.my_page_reward, name="public_userpage_reward"),
    path('group_wait_profile/', view=views.group_wait_profile,
         name='group_wait_profile'),
    path('drop/', views.drop, name="drop"),
    path('drop_success/', views.drop_success, name="drop_success"),
    path('periodic_tasks/', views.periodic_tasks, name="periodic_tasks"),
    path('periodic_tasks_immediate/', views.periodic_tasks_immediate,
         name="periodic_tasks_immediate"),
    path('initialize_rewards/', views.initialize_rewards,
         name="initialize_rewards"),
    path('password_change/search/',
         views.password_change_search, name="password_change_search"),
    path('password_change/<uid64>/<token>/',
         views.password_change, name="password_change"),
]

qna/models.py
from django.db import models
from user.models  import User
from group.models  import *
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCountMixin, HitCount
import os
import urllib

# Create your models here.
class Question(models.Model, HitCountMixin):
    title = models.CharField(verbose_name='제목', max_length=50)
    content = models.TextField(verbose_name='내용')

    # 코드 캡쳐, 실행창 캡쳐와 같은 이미지 업로드
    image = models.ImageField(upload_to='qna/uploads/%Y/%m/%d/', null=True, blank=True)

    # .ent, .sb3 파일 등 소스코드 파일 업로드
    attached_file = models.FileField(verbose_name='첨부파일', upload_to='qna/uploads/%Y/%m/%d/', null=True, blank=True)
    hit = models.IntegerField(verbose_name='조회수', default=0)
    created_at = models.DateTimeField(verbose_name='게시일자', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='수정일자', auto_now=True)
    SE_TAG_CHOICES = (
        ('S', '스크래치'),
        ('E', '엔트리'),
        ('ETC', '기타'),
    )
    s_or_e_tag = models.CharField(verbose_name='기본 카테고리',choices=SE_TAG_CHOICES, max_length=20)

    #### 직성자필드
    user = models.ForeignKey(User, on_delete=models.SET_NULL ,related_name='question_person', null=True, blank=True)
    like_user = models.ManyToManyField('user.User', blank=True)
    tags = models.ManyToManyField('QnaTag', blank=True)

    def __str__(self):
        return self.title

    # html 표시용 filename
    def get_filename(self):
        return os.path.basename(str(self.attached_file))

    # 파일 다운로드 용 filname
    def get_filename_download (self):
        file_name = urllib.parse.quote(self.attached_file.name.split('/')[-1].encode('utf-8'))
        return file_name

    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation'
    )

    def delete(self, *args, **kwargs):
        self.attached_file.delete()
        self.image.delete()
        super(Question, self).delete(*args, **kwargs)

class Answer(models.Model):
    #####
    ### 작성자 필드
    user = models.ForeignKey(User, on_delete=models.SET_NULL ,related_name='answer_person', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='게시일자', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='수정일자', auto_now=True)
    answer_order = models.IntegerField(verbose_name='답변순서')
    answer_depth = models.IntegerField(verbose_name='답변깊이', default=0)

    question_id = models.ForeignKey(Question, on_delete=models.CASCADE,)

    parent_answer = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)

    like_user = models.ManyToManyField('user.User', blank=True)

    is_deleted = models.BooleanField(verbose_name='삭제여부', default=False)

class QnaTag(models.Model):
    # 스크래치 메뉴
    S_TAG_CHOICES = (
        ('MOTION', '동작'),
        ('LOOKS', '형태'),
        ('SOUND', '소리'),
        ('EVENTS', '이벤트'),
        ('CONTROL', '제어'),
        ('SENSING', '감지'),
        ('OPERATORS', '연산'),
        ('VARIABLES', '변수'),
        ('MY', '내 블록'),
        ('ETC', '기타'),
    )

    '''
    # 엔트리 메뉴
    E_TAG_CHOICES = (
        ('START', '시작'),
        ('FLOW', '흐름'),
        ('MOTION', '움직임'),
        ('LOOKS', '생김새'),
        ('BRUSH', '붓'),
        ('SOUND', '소리'),
        ('DECISION', '판단'),
        ('CALCULATE', '계산'),
        ('VARIABLE', '자료'),
        ('FUNCTION', '함수'),
        ('TABLE_AND_AI', '데이터분석 및 인공지능'),
        ('EXTENSION_AND_HARDWARE', '확장 및 하드웨어'),
        ('PYTHON', '엔트리파이썬'),
        ('ETC', '기타'),
    )
    '''
    tag_name = models.CharField(verbose_name='태그',  max_length=20)

    def __str__(self):
        return self.tag_name

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .constants import *
from datetime import datetime
import shutil
# user 대표 이미지


def user_thumbnail_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<email>/<filename>
    return 'user/user_{0}/thumbnail/{1}'.format(instance.email, filename)

# reward 대표 이미지


# def reward_thumbnail_path(instance, filename):
#    # file will be uploaded to MEDIA_ROOT/user_<email>/<filename>
#    return 'reward_{0}/thumbnail/{1}'.format(instance.name, filename)


# 시간
def time_convert(datetimefield):
    data = datetime(datetimefield.year, datetimefield.month, datetimefield.day,
                    datetimefield.hour, datetimefield.minute, datetimefield.second)
    second = int((datetime.now() - data).total_seconds())
    if second > 60 * 60 * 24:
        return str(second // (60 * 60 * 24)) + "일 전"
    elif second > 60 * 60:
        return str(second // (60 * 60)) + "시간 전"
    elif second > 60:
        return str(second // 60) + "분 전"
    else:
        return str(second) + "초 전"


class Reward(models.Model):
    name = models.CharField(max_length=20)
    info = models.TextField()
    type = models.CharField(
        max_length=50, choices=REWARD_TYPE, default='total_like')
    criteria = models.IntegerField(null=True, blank=True)
    img = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def has_reward(self, user):
        if GetReward.objects.get(user=user, reward=self):
            return True
        else:
            return False


class User(AbstractUser):
    email = models.EmailField(verbose_name='email')
    password = models.TextField()
    nickname = models.CharField(max_length=50)
    birth = models.DateField(null=True, blank=True)
    img = models.ImageField(
        upload_to=user_thumbnail_path, null=True, blank=True)
    introduction = models.TextField(null=True, blank=True)
    total_question_like = models.IntegerField(null=True, blank=True, default=0)
    total_comment_like = models.IntegerField(null=True, blank=True, default=0)
    total_question = models.IntegerField(null=True, blank=True, default=0)
    total_answer = models.IntegerField(null=True, blank=True, default=0)
    total_answer_reply = models.IntegerField(null=True, blank=True, default=0)
    level = models.CharField(max_length=50, choices=LEVEL, default='level_1')
    job = models.CharField(max_length=50, choices=JOB_CHOICE, default='etc')
    representative_reward = models.ForeignKey(
        Reward, on_delete=models.CASCADE, null=True, blank=True)

    ### default 이미지 사용 여부를 위한 integer 필드
    default_img = models.CharField(max_length = 15, default='')

    def __str__(self):
        return self.nickname

    def points(self):
        for category in JOB_CATEGORY:
            if self.job in JOB_CATEGORY[category]:
                return (self.total_question_like * POINT[category]['question_like']
                        + self.total_comment_like *
                        POINT[category]['comment_like']
                        + self.total_question * POINT[category]['question']
                        + self.total_answer * POINT[category]['answer']
                        + self.total_answer_reply * POINT[category]['answer_reply'])
        return 0

    def total_like(self):
        return self.total_question_like + self.total_comment_like

    def total_comment(self):
        return self.total_answer + self.total_answer_reply

    def get_level(self):
        current_level = self.level

        for category in JOB_CATEGORY:
            if self.job in JOB_CATEGORY[category]:
                for index in range(len(LEVEL_UP_BOUNDARY[category])):
                    if self.points() >= LEVEL_UP_BOUNDARY[category][index]:
                        level = LEVEL[index]

        if level[0] != current_level:
            if LEVEL_STEP.index(current_level) < LEVEL_STEP.index(level[0]):
                Alert.objects.create(user=self, content="짝짝짝! 레벨이 '{}'로 올라갔어요!".format(
                    LEVEL[LEVEL_STEP.index(level[0])][1]), alert_type="level_up", time=datetime.now())
            else:
                Alert.objects.create(user=self, content="레벨이 '{}'로 변경되었어요.".format(
                    LEVEL[LEVEL_STEP.index(level[0])][1]), alert_type="level_change", time=datetime.now())

        self.level = level[0]
        self.save()
        return level[1]

    def has_new_alert(self):
        new_alert_num = 0
        for alert in Alert.objects.filter(user=self):
            if not alert.checked:
                new_alert_num += 1
        return new_alert_num

    def get_new_alert(self):
        return Alert.objects.filter(user=self, checked=False).order_by('-time')[:3]

    def mypage_description(self):
        my_category = ''
        description = [['열심히 활동해서 포인트를 모으면 레벨을 높일 수 있어요!'], ["특히 '❤ 좋아요'를 받으면 더 많은 점수를 얻을 수 있으니,"], ["'묻고 답하기' 게시판에서 좋은 질문과 답변을 열심히 적어보아요:)"],
                       ['(* 어린이 회원과 어른 회원의 레벨, 포인트 체계가 다르답니다.)'], ['─'], ['💛 레벨 체계']]
        for category in JOB_CATEGORY:
            if self.job in JOB_CATEGORY[category]:
                my_category = category
        description += [level_description(my_category)]
        description += [['─'], ['💛 포인트 체계']]
        description += [point_description(my_category)]
        description += [['─'], ['💛 나의 현황'], [self.nickname +
                        " 님의 현재 레벨은 " + self.get_level() + ", 포인트는 " + str(self.points()) + "점입니다."]]
        if LEVEL_STEP.index(self.level) == len(LEVEL) - 1:
            description += [["이미 최고 레벨에 도달했어요!"]]
        else:
            description += [["다음 레벨까지 " + str(
                LEVEL_UP_BOUNDARY[my_category][LEVEL_STEP.index(self.level) + 1] - self.points()) + "점이 더 필요해요!"]]
        return description

    def delete(self, *args, **kwargs):
        user_dir = './media/user/user_{0}/'.format(self.email)
        super(User, self).delete(*args, **kwargs)
        shutil.rmtree(user_dir)
        


class GetPoint(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(
        max_length=50, choices=POINT_TYPE, default='question_like')
    point = models.IntegerField(null=True, blank=True)
    get_date = models.DateTimeField()

    def time_past(self):
        return time_convert(self.get_date)


# 업적 만들기 (현재는 예시임 테스트용)


def initializeReward():
    for REWARD in REWARD_ALL:
        if not Reward.objects.filter(name=REWARD[0]):
            Reward.objects.create(
                name=REWARD[0], info=REWARD[1], type=REWARD[2], criteria=REWARD[3], img=REWARD[4])


class GetReward(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reward = models.ForeignKey(Reward, on_delete=models.CASCADE)
    get_date = models.DateTimeField()


class Alert(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    alert_type = models.CharField(
        max_length=50, choices=ALERT_TYPE, default='etc')
    time = models.DateTimeField()
    related_id = models.CharField(max_length=100, default='')
    checked = models.BooleanField(default=False)

    def related_url(self):
        if self.alert_type in ['new_comment_qna', 'new_reply_qna']:
            # related_id : question id
            return '/qna/{}/'.format(self.related_id)
        elif self.alert_type in ['new_comment_group', 'new_reply_group']:
            # related_id : group id + " " + post id
            return '/group/{}/post_detail/{}'.format(self.related_id.split(" ")[0], self.related_id.split(" ")[1])
        elif self.alert_type in ['level_up', 'level_change']:
            return '/mypage/point/'
        elif self.alert_type in ['get_reward']:
            return '/mypage/reward/{}/'.format(self.user.id)
        elif self.alert_type in ['group_create', 'group_join', 'group_reject', 'group_register', 'group_maker']:
            # if Group.objects.filter(pk=self.related_id):
            return '/group/{}/group_detail/'.format(self.related_id)
            # else:
            #    return '#'
        else:
            return '#'

    def time_past(self):
        return time_convert(self.time)

templates/user/drop.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/singup_success.css' %}">
{% endblock %}

{% block title %} 도와줘, 코딩 | 회원 탈퇴 {% endblock %}

{% block content %}

<div class="email__box">
    <span class="email-text">{{ email }}</span>
</div>

<div class="signup__success">
    <p class="signup__success--message">
    <span>정말로 회원 탈퇴를 하실 건가요?</span>
    <span>'탈퇴하기' 버튼을 누르면 가입한 이메일로 확인 이메일이 발송되며</span>
    <span>월요일 자정 전까지 해당 메일을 열어 링크를 클릭하면 탈퇴 취소를 할 수 있어요.</span>
    </p>
    <div>
      <a class="return-main__btn" href="{% url 'user:mypage' %}">취소하기</a>
      <a class="drop__btn" href="{% url 'user:drop_success' %}">탈퇴하기</a>
    </div>
</div>

{% endblock content %}

templates/user/drop_success.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/singup_success.css' %}">
{% endblock %}

{% block title %} 도와줘, 코딩 | 회원 탈퇴 완료 {% endblock %}

{% block content %}

<div class="email__box">
    <span class="email-text">{{ email }}</span>
</div>

<div class="signup__success">
    <p class="signup__success--message">
    <span>도와줘 코딩 사이트를 이용해주셔서 감사합니다.</span>
    <span>언제든지 코딩 중에 어려움이 있다면 도와줘 코딩 사이트로 다시 놀러와주세요.</span>
    <span>(월요일 자정 전까지 발송된 메일을 열어 링크를 클릭하면 언제든지 탈퇴 취소를 할 수 있어요.)</span>
    </p>
    <a class="return-main__btn" href="{% url 'user:main' %}">메인으로</a>
</div>

{% endblock content %}

templates/user/login.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/signup_login.css' %}">
{% endblock css %}
{% block title %} 도와줘, 코딩 | 로그인 {% endblock %}

{% block content %}
<div class="login__container">
    <h1>도와줘코딩 로그인</h1>
    <form method="POST" action="">
        <div class="login__innercontainer">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="login__loginbtn">로그인</button>
        </div>
    </form>
    <button class="bluebtn"><a href="{% url 'user:password_change_search' %}">비밀번호를 잊어버렸어요</a></button>
</div>
<script>
    const emailLabel = document.querySelector('label[for="id_email"]');
    const pwLabel = document.querySelector('label[for="id_password"]');
    emailLabel.textContent = '이메일';
    pwLabel.textContent = '비밀번호';
</script>
{% endblock content %}

templates/user/mypage_question.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/mypage.css' %}">
{% endblock css %}

{% block js %}
    <script src="{% static 'js/user_profile_redirect.js' %}" defer></script>
{% endblock %}

{% block title %} 도와줘, 코딩 | 질문 기록 {% endblock %}

{% block content %}
<div>
  <div class="mypage__question__container" style="display: block;">
    <div class="mypage__title">
      <h3>질문 기록</h3>
    </div>
    {% if questions %}
    {% for question in questions %}
    <a href="{% url 'qna:question_detail' question.pk %}" class="mypage__question">
      <div class="mypage__question-left">
        <p class="mypage__question__title">{{ question.title }}</p>
        <p class="mypage__question__content">{{ question.content }}</p>
      </div>
      <div class="mypage__question-right">
        <div>답변</div>
        <div>
          {{ question.answer_set.all | length }}
        </div>
      </div>
    </a>
    {% endfor %}
    {% else %}
    <p>질문 기록이 없어요🥺</p>
    {% endif %}
    <div class="mypage__bottom-btn">
      <button class="bluebtn"><a id="profile-redirect" href="{% url 'user:mypage' %}" style="text-decoration: none">마이페이지로 돌아가기</a></button>
      <button id="profile-go-qna" class="bluebtn"><a href="{% url 'qna:question_list' %}" style="text-decoration: none">질문하러 가기</a></button>
    </div>
  </div>

<!-- 페이지네이션 -->
{% if is_paginated %}
<div class="pagination-box">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="all__page-sign" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
          <path d="M12.7688 22.5918L2.02827 11.8513L12.7688 1.11076" stroke="#C4C4C4" stroke-width="2"/>
        </svg>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="all__page-sign" href="#" tabindex="-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
          <path d="M12.7688 22.5918L2.02827 11.8513L12.7688 1.11076" stroke="#C4C4C4" stroke-width="2"/>
        </svg>
      </a>
    </li>
    {% endif %}
    
    {% if page_obj.number|add:'-2' > 1 and page_obj.paginator.num_pages > 5 %}
      <li class="page-item">
          <a class="page-link" href="?{% param_replace page=page_obj.number|add:'-5' %}">
              ...
          </a>
      </li>
    {% endif %}
      
      {% for page_number in page_range %}
        {% if page_number == page_obj.number %}
          <li class="page-item">
            <a class="page-link page-item-active" href="?{% param_replace page=page_number %}">
              {{ page_number }}
            </a>
          </li>
        {% else %}
          {% if page_obj.number < 4 %}
            {% if page_number < 6 %}
              <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_number %}">{{ page_number }}</a>
              </li>
            {% endif %}
          {% elif page_obj.number > page_obj.paginator.num_pages|add:'-2' %}
            {% if page_number > page_obj.paginator.num_pages|add:'-5' %}
              <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_number %}">{{ page_number }}</a>
              </li>
            {% endif %}
          {% else %}
            {% if page_number > page_obj.number|add:'-3' and page_number < page_obj.number|add:'3' %}
              <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_number %}">{{ page_number }}</a>
              </li>
            {% endif %}
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.paginator.num_pages > page_obj.number|add:'2' and page_obj.paginator.num_pages > 5 %}
        <li class="page-item">
            <a class="page-link" href="?{% param_replace page=page_obj.number|add:'5' %}">
                ...
            </a>
        </li>
      {% endif %}
    
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="all__page-sign sign-next" href="?page={{ page_obj.next_page_number }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
          <path d="M1.23096 1.11035L11.9715 11.8509L1.23096 22.5914" stroke="#C4C4C4" stroke-width="2"/>
          </svg>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="all__page-sign" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" viewBox="0 0 14 24" fill="none">
          <path d="M1.23096 1.11035L11.9715 11.8509L1.23096 22.5914" stroke="#C4C4C4" stroke-width="2"/>
          </svg>
      </a>
    </li>
    {% endif %}
  </ul>
  {% endif %}
</div>

</div>
{% endblock content %}

templates/user/password_change_email_sent.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/singup_success.css' %}">
{% endblock %}

{% block title %} 도와줘, 코딩 | 비밀번호 변경 {% endblock %}

{% block content %}

<div class="email__box">
    <span class="email-text">{{ email }}</span>
</div>

<div class="signup__success">
    <p class="signup__success--message">
    <span>위의 주소로 비밀번호 변경 메일이 발송되었어요.</span>
    <span>가입한 이메일 주소로 로그인한 후, 메일을 열어 링크를 클릭해주세요!</span>
    <span></span>
    <span>※ 이메일이 오지 않은 경우 스팸 메일함을 확인해주세요. ※</span>
    </p>
    <a class="return-main__btn" href="{% url 'user:main' %}">메인으로 돌아가기</a>
</div>

{% endblock content %}

templates/user/password_change_success.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/singup_success.css' %}">
{% endblock %}

{% block title %} 도와줘, 코딩 | 비밀번호 변경 {% endblock %}

{% block content %}

<div class="email__box">
    <span class="email-text">{{ email }}</span>
</div>

<div class="signup__success">
    <p class="signup__success--message">
    <span>비밀번호가 변경되었어요!</span>
    <span>아래 버튼을 눌러 다시 로그인해주세요.</span>
    </p>
    <a class="return-main__btn" href="{% url 'user:login' %}">로그인하러 가기</a>
</div>

{% endblock content %}

templates/user/user_drop_email.html
{% autoescape off %}

〔도와줘, 코딩〕 사이트를 이용해주셔서 감사합니다.

월요일 자정에 회원탈퇴 처리가 되며, 그 이전까지 아래 링크를 누르면 회원탈퇴를 취소하고 사이트를 다시 이용하실 수 있습니다.

▶ 회원탈퇴 취소 링크 : http://{{ domain }}{% url 'user:activate' uid64=uid token=token %}

{% endautoescape %}

templates/user/user_password_change_email.html
{% autoescape off %}

〔도와줘, 코딩〕 사이트 비밀번호 변경 메일입니다.

아래 링크를 클릭한 후 새 비밀번호를 만들어주세요.

▶ 비밀번호 변경 링크 : http://{{ domain }}{% url 'user:password_change' uid64=uid token=token %}

{% endautoescape %}